version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@9.0
  aws-cli: circleci/aws-cli@5.1

workflows:
  build-and-push:
    jobs:
      - aws-ecr/build_and_push_image:
          auth:
            - aws-cli/setup:
                role_arn: arn:aws:iam::123456789012
          repo: 'my-ecr-repo'
          tag: '${CIRCLE_SHA1}'
          region: 'us-west-2'
